### PR TITLE
Issue 26

### PR DESCRIPTION
**Pull request by ibrahimtaib**
Adding a fix to checking if an application already exists. There are the backend functions, and frontend logic. The frontend does seem sometimes broken, i'm not sure if it comes from the authentication, from a lack of error handling, or if i broke something, so I invite you to really test it since you know best.

### CODE REVIEW

**Review by frabacc — COMMENTED** [review]
I will review it at home. I'll pull from this repo and check. What are the issues?

**Comment by frabacc** [comment]
it works, we need to modify some stuff in the front-end (for example we should indicate that the proposal has already expired (or should we have a expired tab somewhere?) let me know what you think.

**Comment by ibrahimtaib** [comment]
I think that comes later , story 12 and 15. If this is fixed we can merge

**Review by frabacc — APPROVED** [review]
LGTM!

**Pull request merged**
