### PR TITLE
Create frontend (insert proposal)

### PR DESCRIPTION
**Pull request by frabacc**
First part of the frontend (adding also dependencies and stuff) is ready. I think that we can merge with main so other members can pull and take inspiration from that.

### CODE REVIEW

**Comment by ibrahimtaib** [comment]
It looks great!
Do you think you can make it so the expiration date cannot be earlier than the current date?

We might also have to check if we're able to turn the co-supervisor input into one that shows a drop list of possible co-supervisors (there's surely existing components that do this already), but it's up to you to see if you think you should just add a TODO for later or check it when you have some time.

And this is just a personal opinion, there's a text saying "write a small description about the thesis" but it's under the input box, I would either put it above the input or maybe not put it at all, since the placeholder for the input already explains that they should write a small description.

Tell me what you think about my suggestions!

**Comment by jouchaib2020** [comment]
Hey, 
Thanks for the code Francessco, I think it's not ready yet to be merged in main cuz it needs to be fully worknig a.k.a adding a proposal to the database when add is clicked
I am working on that as well as some small adjustments on the code it's self

**Comment by jouchaib2020** [comment]
Yeah and I think you forgot to add unit tests

**Comment by ibrahimtaib** [comment]
Can I close this pull request until later?

**Comment by frabacc** [comment]
I think that the branch is ready to be merged. Everything works flawlessly  and I've added also some instruction on how to execute it. We can make the other pages based on this one I think.

**Review by jouchaib2020 — APPROVED** [review]
LGTM !

**Pull request merged**
